variable "resource_prefix"   {}
variable "cluster_name"      {}
variable "cluster_node_name" {}
variable "node_type"         {}
variable "vpc_id"            {}
variable "subnet_id1"        {}
variable "subnet_id2"        {}
variable "node_desired_size" {}
variable "node_max_size"     {}
variable "node_min_size"     {}
variable "aws_region"        {}
